# Generated by Django 3.1.7 on 2021-03-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210324_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf_aluno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='endereco',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='serie_aluno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
