# Generated by Django 3.1.7 on 2021-03-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210330_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletype',
            name='bairro',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profiletype',
            name='cep',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profiletype',
            name='cidade',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profiletype',
            name='estado',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profiletype',
            name='rua',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profiletype',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
