# Generated by Django 3.1.7 on 2021-03-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210330_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiletype',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='profiletype',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='profiletype',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='profiletype',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='profiletype',
            name='rua',
        ),
        migrations.AddField(
            model_name='profile',
            name='bairro',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cep',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cidade',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='estado',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rua',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
