# Generated by Django 3.1.7 on 2021-03-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210330_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
