# Generated by Django 3.1.7 on 2021-03-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_donate_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='numero',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
