# Generated by Django 3.1.7 on 2021-03-30 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210329_1405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemType',
            new_name='Item',
        ),
        migrations.AddField(
            model_name='itemselection',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.item'),
        ),
        migrations.AddField(
            model_name='itemselection',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
        migrations.AlterField(
            model_name='itemselection',
            name='item_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='itemselection',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='itemselection',
            name='donate',
        ),
        migrations.RemoveField(
            model_name='itemselection',
            name='item_type',
        ),
    ]
