# Generated by Django 3.1.7 on 2021-03-30 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210330_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemselection',
            name='item_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_selection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.itemselection')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
    ]
