# Generated by Django 3.1.7 on 2021-03-30 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210330_1537'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='StudentList',
        ),
    ]
